config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users
  #match '/users',   to: 'users#index',   via: 'get'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  
  
 
  #resources :users, only: [:index, :show, :edit, :update, :destroy]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets
  
  resources :drivers
  
  resources :departments
  root to: "tickets#index"
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Department < ApplicationRecord
  has_many :users

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
  end
  
  def show
    @department = Department.find(params[:id])
    
  end
  
  def new
    @department = Department.new
  end
  
  def create
    @department = Department.new(department_params)

    if @department.save
      
      flash[:success] = "Unidade cadastrada com sucesso!"
      redirect_to @department
    else
      render 'new'
    end
  end
  
  def edit 
    @department = Department.find(params[:id])
  end
  
  def update
    @department = Department.find(params[:id])
    if @department.update_attributes(department_params)
      flash[:success] = "Unidade atualizada!"
      redirect_to @department
    else
      render 'edit'
    end
  end
  
  def destroy
    Department.find(params[:id]).destroy
    flash[:success] = "Grupo deletado!"
    redirect_to departments_url
  end
  
  private
  
  def department_params
    params.require(:department).permit(:name)
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<li>
  <%= link_to department.name, department %>  
  
  <%# if current_user.admin? && !current_user?(user) %>
    <%= link_to "Apagar", department,  method: :delete, data: { confirm: "Tem certeza?" } %>
  <%# end %>
</li>

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome" %>
        <%= f.text_field :name, { class: 'form-control' } %>
        <%= f.submit "Gravar", class: "margin-top btn btn-primary" %>
      <% end %>

app/views/departments/edit.html.erb
<div class ="container">
  <h1>Editar Unidade</h1>
</div>

<div class="row">                                                                                                                                                                               
  <div class="col-md-3 col-md-offset-4">                                                                                                                                                        
    <%= render 'form' %>
  </div>
</div>

app/views/departments/index.html.erb
<div class="container">
  <h1>Unidades</h1>
  <ul class="departments">
    <% @departments.each do |department| %>
      <li>
        <%= link_to department.name, department %>
        <% if current_user.role_id == 4 %>
             | <%= link_to "Editar", edit_department_path(department) %> 
          <%#= link_to "Excluir", department, method: :delete, data: { confirm: "Tem certeza?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
  
</div>

app/views/departments/new.html.erb
<div class ="container">
  <h1>Criar Unidade</h1>
</div>

<div class="row">                                                                                                                                                                               
  <div class="col-md-3 col-md-offset-4">                                                                                                                                                        
    <%= render 'form' %>
  </div>
</div>

app/views/departments/show.html.erb
<div class="container">
<p>Nome da unidade: <%= @department.name %></p>
<%= link_to "Listar Unidades", departments_path %>
</div>