config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users
  #match '/users',   to: 'users#index',   via: 'get'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  
  
 
  #resources :users, only: [:index, :show, :edit, :update, :destroy]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets
  
  resources :drivers
  
  resources :departments
  root to: "tickets#index"
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id                  :integer          not null, primary key
#  start_date          :datetime
#  return_date         :datetime
#  rate                :decimal(, )
#  price               :decimal(, )
#  annotation          :text
#  status              :string
#  department_id       :integer
#  origin_id           :string
#  destination_id      :string
#  driver_id           :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  origin_city_id      :string
#  destination_city_id :string
#  manager             :string
#  day                 :integer
#  user_id             :integer
#  deleted_at          :datetime
#

class Ticket < ApplicationRecord
  
  acts_as_paranoid without_default_scope: true
  belongs_to :driver, optional: true
  belongs_to :department, optional: true
  belongs_to :state, optional: true
  belongs_to :city, optional: true
  belongs_to :user, optional: true
  accepts_nested_attributes_for :user
  
  validates_presence_of :driver_id
  
  before_save { self.price.to_s.gsub(',','.').to_f }

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |ticket|
        csv << ticket.attributes.values_at(*column_names)
      end
    end
  end


end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  #before_action :logged_in_user, only: [:create, :destroy, :index]
  #load_and_authorize_resource
  before_action :logged_in_user
  before_action :correct_user, only: :destroy
  before_action :admin_user, only: [:edit, :update]
  layout "print", only: :show

  def index
    @search = Ticket.ransack(params[:q])
    #@tickets = Ticket.all.without_deleted
    @tickets = @search.result.without_deleted
    respond_to do |format|
      format.html
      format.csv { send_data @tickets.to_csv }
      format.xls # { send_data @tickets.to_csv(col_sep: "\t") }
    end
    #@search.build_condition
    #@people = @q.result.includes(:articles).page(params[:page])
    
    
  end

  def show
    @ticket = Ticket.find(params[:id])
    #@total = totalprice
    
  end
    
  def edit 
    @ticket = Ticket.find(params[:id])
    #authorize! :edit, @ticket
    
  end
  
  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update_attributes(ticket_params)
      redirect_to @ticket
      return
    else
      render 'edit'
      return
    end      
  end

  def new
    @ticket = Ticket.new
    @user = current_user
  
    
  end
  
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    
    if @ticket.save
      #CommentMailer.reply_ticket(@ticket).deliver_now
      redirect_to tickets_path
    else
      render :new
    end
  end


  
  
  

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    if @ticket.destroy
      flash[:error] = "Requisição Apagada!"
      redirect_to @ticket
#      redirect_to root_url, notice: "Requisição deletada!"
    end
  end



  private
  
    # Confirms the correct user.

  
  def correct_user
  @ticket = current_user.tickets.find_by(id: params[:id])
  if current_user.role_id == 4 || current_user?(@ticket)
  else
  redirect_to root_url if @ticket.nil?
end
end

  

  def ticket_params
    #params.require(:ticket).permit(:subject, :body, :status, :department_id, :user_id, :type_id, comments_attributes: [:content, :user_id])
    params.require(:ticket).permit(:start_date, :return_date, :rate, :price, :annotation, :status, :department_id,
      :origin_id, :origin_city_id, :driver_id, :destination_id, :destination_city_id)
  end
  
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_admin.html.erb
<div class="container">


  <div class="row">
    <%= search_form_for @search do |f| %>
    
    <%#= f.search_field :created_at_gteq, 'datepicker' => true  %>
    <div class="col-md-8">
      <div class="order-table table form-group form-inline margin-top margin-bottom">                
        <%= f.label :created_at_gteq, "Criado Entre" , class: 'control-label ' %>
      <%= f.text_field :created_at_gteq, class: 'form-control datetimepicker4 ' %>
      <%= f.label :created_at_lteq, "e" %>
      <%= f.search_field :created_at_lteq, class: 'form-control datetimepicker4' %>
      <%= f.submit "Filtrar Datas" %>
      <% end %>
      </div>
    </div>
  </div>
</div>
  
<div class="container text-right">
<p>
  Download:
  <%= link_to "CSV", tickets_path(format: "csv") %> |
  <%= link_to "Excel", tickets_path(format: "xls") %>
</p>
</div>
<div class="container">
  
	<div class="row">
		<div class="span5">
		  <!-- <input type="text" id="search" placeholder="Digite para filtrar"> -->
      
      <table id="mytable" class="table table-striped table-condensed">

        <thead>
          <tr>
            <th>N° Requisição</th>
            <th>Data</th>
            <th>Unidade</th>
            <th>Origem</th>
            <th>Início</th>
            <th>Destino</th>
            <th>Retorno</th>
            <th>Motorista</th>
            <th>Diárias</th>
            <th>Total</th>
            <th>Status</th>
          </tr>
        </thead>
  <tbody>
  <!-- <tbody data-update-url="<#%= sort_tickets_url %>"> -->
        <% @tickets.each do |ticket| %>
          <tr>
            <td><%= ticket.id %>
              <%# if can? :update, @article %>
              <% if current_user.role_id == 4 %>
                <%= link_to "Editar", edit_ticket_path(ticket) %> | 
                <%= link_to "Excluir", ticket, method: :delete,
                      data: { confirm: "Tem certeza?" } %>
              <% end %>
              <% if current_user?(ticket.user) && current_user.role_id == 3 %>
                <%#= link_to "Excluir", ticket, method: :delete,                       data: { confirm: "Tem certeza?" } %>
                | <%= link_to "Excluir", ticket, method: :delete, data: { confirm: "Tem certeza?" } %>
              <% end %>
            </td>
            <td><%= ticket.created_at.strftime("%d/%m/%Y") %></td>    
            <%#= link_to "Apagar", ticket,  method: :delete, data: { confirm: "Tem certeza?" } %>
            <% if ticket.user.department.nil? %>
              <td></td>
              <% else %>
                <td><%= ticket.user.department.name %></td>
              <% end %>
            <td><%= ticket.origin_city_id %> - <%= ticket.origin_id %></td>
            <td><%= ticket.start_date.strftime("%d/%m/%Y %H:%M")  %></td>
            <td><%= ticket.destination_city_id %> - <%= ticket.destination_id %> </td>
            <td><%= ticket.return_date.strftime("%d/%m/%Y %H:%M") %></td>
            <td><%= ticket.try(:driver).try(:name) %></td>
            <td><%= ticket.rate %></td>
            <%#= ticket.price.number_to_currency(9.99, :separator => ",", :delimiter => ".", :unit => "R$") %>
            <td><%= number_to_currency(ticket.price, :unit => "R$ ", :separator => ",", :delimiter => ".")%></td>

            <% if ticket.status == 'Aberto' %>
              <td><span class="label label-danger"><%= ticket.status %></span></td>
              <% elsif ticket.status == 'Analisando' %>
                <td><span class="label label-warning"><%= ticket.status %></span></td>
                <% else %>
                <td><span class="label label-success"><%= link_to ticket.status, 
                    ticket, {style: "color: white"} %></span></td>
                
              <% end %>
          </tr>
        <% end %>
    </tbody>

    </div>
	</div>
</div>

app/views/tickets/_editor.html.erb
<div class="container">


  <div class="row">
    <%= search_form_for @search do |f| %>
    
    <%#= f.search_field :created_at_gteq, 'datepicker' => true  %>
    <div class="col-md-8">
      <div class="order-table table form-group form-inline margin-top margin-bottom">                
        <%= f.label :created_at_gteq, "Criado Entre" , class: 'control-label ' %>
      <%= f.text_field :created_at_gteq, class: 'form-control datetimepicker4 ' %>
      <%= f.label :created_at_lteq, "e" %>
      <%= f.search_field :created_at_lteq, class: 'form-control datetimepicker4' %>
      <%= f.submit "Filtrar Datas" %>
      <% end %>
      </div>
    </div>
  </div>
</div>
  
<div class="container text-right">
<p>
  Download:
  <%= link_to "CSV", tickets_path(format: "csv") %> |
  <%= link_to "Excel", tickets_path(format: "xls") %>
</p>
</div>
<div class="container">
  
	<div class="row">
		<div class="span5">

      
      <table id="mytable" class="table table-striped table-condensed">

        <thead>
          <tr>
            <th>N° Requisição</th>
            <th>Data</th>
            <th>Unidade</th>
            <th>Origem</th>
            <th>Início</th>
            <th>Destino</th>
            <th>Retorno</th>
            <th>Motorista</th>
            <th>Diárias</th>
            <th>Total</th>
            <th>Status</th>
          </tr>
        </thead>
        
        <tbody>
          <% @tickets.each do |ticket| %>
            
              <% if ticket.user.department.nil? %>
                <%# ticket sem departamento %>
              <% else %>
                <% if current_user?(ticket.user) && current_user.department.name == ticket.user.department.name %>
                <tr>
                  <!-- COMECA -->
                  <td><%= link_to ticket.id, ticket %>
                  <% if current_user.role_id == 4 %>
                    <%= link_to "Editar", edit_ticket_path(ticket) %> | 
                    <%= link_to "Excluir", ticket, method: :delete,
                        data: { confirm: "Tem certeza?" } %>
                  <% end %>
                  <% if current_user?(ticket.user) && current_user.role_id == 3 %>
                    | <%= link_to "Excluir", ticket, method: :delete, data: { confirm: "Tem certeza?" } %>
                  <% end %>
                  </td>
                  <td><%= ticket.created_at.strftime("%d/%m/%Y") %></td>    
                  <%#= link_to "Apagar", ticket,  method: :delete, data: { confirm: "Tem certeza?" } %>
                  <% if ticket.user.department.nil? %>
                    <td></td>
                  <% else %>
                    <td><%= ticket.user.department.name %></td>
                  <% end %>
                  <td><%= ticket.origin_city_id %> - <%= ticket.origin_id %></td>
                  <td><%= ticket.start_date.strftime("%d/%m/%Y %H:%M")  %></td>
                  <td><%= ticket.destination_city_id %> - <%= ticket.destination_id %> </td>
                  <td><%= ticket.return_date.strftime("%d/%m/%Y %H:%M") %></td>
                  <td><%= ticket.try(:driver).try(:name) %></td>
                  <td><%= ticket.rate %></td>
                  <%#= ticket.price.number_to_currency(9.99, :separator => ",", :delimiter => ".", :unit => "R$") %>
                  <td><%= number_to_currency(ticket.price, :unit => "R$ ", :separator => ",", :delimiter => ".")%></td>

                  <% if ticket.status == 'Aberto' %>
                    <td><span class="label label-danger"><%= ticket.status %></span></td>
                  <% elsif ticket.status == 'Analisando' %>
                      <td><span class="label label-warning"><%= ticket.status %></span></td>
                  <% else %>
                    <td><span class="label label-success"><%= link_to ticket.status, 
                    ticket, {style: "color: white"} %></span></td>
                  <% end %>
                  <!-- TERMINA -->
                <% end %>
              <% end %>
          
        
              
            
            </tr>
          <% end %>
        </tbody>
      
    </div>
	</div>
</div>

app/views/tickets/_form.html.erb
 
 <%= form_for (@ticket) do |f| %>
  
  <div class="col-md-6 col-md-offset-3 well">
  
    <%= f.label :driver_id, "Motorista" %>
    <%= f.collection_select(:driver_id, Driver.all, :id, :name, {:include_blank => true}, {:class=> "form-control margin-bottom"}) %>
  
      
    <div class="row">
      <div class="col-md-6">    
        <%= f.label :origin_id, "Origem"%>
        <%= f.collection_select(:origin_id, State.all, :symbol, :name, {:include_blank => true}, {:class=> "jstates form-control "}) %>
      </div>
      <div class="col-md-6">
        <%= f.label :origin_city_id, "Cidade"%>
        <%= f.grouped_collection_select :origin_city_id, State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {:class=> "jcities form-control "} %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">          
        <%= f.label :destination_id, "Destino" %>
        <%= f.collection_select(:destination_id, State.all, :symbol, :name, {:include_blank => true}, {:class=> "form-control jstates"}) %>
      </div>
      <div class="col-md-6">          
        <%= f.label :destination_city_id, "Cidade" %>
        <%= f.grouped_collection_select :destination_city_id, State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {:class=> "jcities form-control margin-bottom"} %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <%= f.label :start_date, "Saída" %>
        <%#= f.datetime_select :start_date, {:minute_step => 10}, {:id => 'datetimepicker'} %>
        <%#= f.text_field :start_date, { :class=> "form-control", :id=>"datetimepicker3"} %>
        <%= f.text_field :start_date, { :class=> "form-control datetimepicker1"} %>
      </div>
      <div class="col-md-6">
        <%= f.label :return_date, "Retorno" %>
        <%#= f.datetime_select :return_date, :minute_step => 10 %>
        <%= f.text_field :return_date, { :class=> "form-control datetimepicker2" } %>
      </div>
    </div>

    <%= f.label :Mensagem %>
    <%= f.text_area :annotation, class: "form-control", style: "height:300x" %>
    
    <div class="row">
      <div class="col-md-6">   
        <%= f.label :rate, "Qtd. Diárias"%>
        <%= f.text_field :rate, class: "form-control"%>
      </div>
      <div class="col-md-6">   
        <%= f.label :price, "Valor"%>
        <%= f.text_field :price, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">   
      <%= f.label :status %>
      <%= f.select :status, ['Aberto', 'Analisando',  'Pago'], {}, {:class=> "form-control margin-bottom"} %>
      </div>
    <div class="col-md-8">
      <%= f.submit "Salvar Requisição", class: "btn btn-primary form-control margin-top" %>
    </div>
    <% end %>
  
</div>

app/views/tickets/edit.html.erb
<script type="text/javascript">
  $(function () {
    $('.datetimepicker1').datetimepicker({
      defaultDate: "<%= @ticket.start_date %>",
      format: "DD-MM-YYYY HH:mm"
    });
  });
  
    $(function () {
    $('.datetimepicker2').datetimepicker({
      defaultDate: "<%= @ticket.return_date %>",
      format: "DD-MM-YYYY HH:mm"
    });
  });

</script>

<%= form_for (@ticket) do |f| %>
  
  <div class="col-md-6 col-md-offset-3 well">
  
    <%= f.label :driver_id, "Motorista" %>
    <%= f.collection_select(:driver_id, Driver.all, :id, :name, {:include_blank => true}, {:class=> "form-control margin-bottom"}) %>
  
      
    <div class="row">
      <div class="col-md-6">    
        <%= f.label :origin_id, "Origem"%>
        <%= f.collection_select(:origin_id, State.all, :symbol, :name, {:include_blank => true}, {:class=> "jstates form-control "}) %>
      </div>
      <div class="col-md-6">
        <%= f.label :origin_city_id, "Cidade"%>
        <%= f.grouped_collection_select :origin_city_id, State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {:class=> "jcities form-control "} %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">          
        <%= f.label :destination_id, "Destino" %>
        <%= f.collection_select(:destination_id, State.all, :symbol, :name, {:include_blank => true}, {:class=> "form-control jstates"}) %>
      </div>
      <div class="col-md-6">          
        <%= f.label :destination_city_id, "Cidade" %>
        <%= f.grouped_collection_select :destination_city_id, State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {:class=> "jcities form-control margin-bottom"} %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <%= f.label :start_date, "Saída" %>
        <%#= f.datetime_select :start_date, {:minute_step => 10}, {:id => 'datetimepicker'} %>
        <%#= f.text_field :start_date, { :class=> "form-control", :id=>"datetimepicker3"} %>
        <%= f.text_field :start_date, { :class=> "form-control datetimepicker1"} %>
      </div>
      <div class="col-md-6">
        <%= f.label :return_date, "Retorno" %>
        <%#= f.datetime_select :return_date, :minute_step => 10 %>
        <%= f.text_field :return_date, { :class=> "form-control datetimepicker2" } %>
      </div>
    </div>

    <%= f.label :Mensagem %>
    <%= f.text_area :annotation, class: "form-control", style: "height:300x" %>
    
    <div class="row">
      <div class="col-md-6">   
        <%= f.label :rate, "Qtd. Diárias"%>
        <%= f.text_field :rate, class: "form-control"%>
      </div>
      <div class="col-md-6">   
        <%= f.label :price, "Valor"%>
        <%= f.text_field :price, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">   
      <%= f.label :status %>
      <%= f.select :status, ['Aberto', 'Analisando',  'Pago'], {}, {:class=> "form-control margin-bottom"} %>
      </div>
    <div class="col-md-8">
      <%= f.submit "Confirmar Mudanças", class: "btn btn-primary form-control margin-top" %>
    </div>
    <% end %>
  
</div>

app/views/tickets/index.html.erb
<script type="text/javascript">
            
  $(function () {
    $('.datetimepicker4').datetimepicker({
      format: "L"
    });
  });

</script>

<h1 class="text-center">Controle de Requisição</h1>

<% if current_user.role_id == 4 %>
  <%= render 'admin' %>
  <% else %>
  <%= render 'editor' %>
<% end %>

app/views/tickets/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">N° Requisição</Data></Cell>
        <Cell><Data ss:Type="String">Data</Data></Cell>
        <Cell><Data ss:Type="String">Unidade</Data></Cell>
        <Cell><Data ss:Type="String">Origem</Data></Cell>
        <Cell><Data ss:Type="String">Saída</Data></Cell>
        <Cell><Data ss:Type="String">Destino</Data></Cell>
        <Cell><Data ss:Type="String">Retorno</Data></Cell>
        <Cell><Data ss:Type="String">Motorista</Data></Cell>
        <Cell><Data ss:Type="String">Diárias</Data></Cell>
        <Cell><Data ss:Type="String">Total</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
      </Row>

<% @tickets.each do |ticket| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= ticket.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.created_at.strftime("%d/%m/%Y") %></Data></Cell>
        <% if ticket.user.department.nil? %>
          <Cell><Data ss:Type="String"></Data></Cell>
          <% else %>
            <Cell><Data ss:Type="String"><%= ticket.user.department.name %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="String"><%= ticket.origin_city_id %> - <%= ticket.origin_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.start_date.strftime("%d/%m/%Y %H:%M") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.destination_city_id %> - <%= ticket.destination_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.return_date.strftime("%d/%m/%Y %H:%M") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.try(:driver).try(:name) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.rate %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.price %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ticket.status %></Data></Cell>
            
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>
        

app/views/tickets/new.html.erb
<script type="text/javascript">
            
$(function () {
    $('.datetimepicker4').datetimepicker();
            });
  
</script> 
<div class="container">
  <legend>Requisição de Diárias de Motoristas</legend>
</div>

 <%= form_for (@ticket) do |f| %>
  
  <div class="col-md-6 col-md-offset-3 well">
  
    <%= f.label :driver_id, "Motorista" %>
    <%= f.collection_select(:driver_id, Driver.all, :id, :name, {:include_blank => true}, {:class=> "form-control margin-bottom"}) %>
  
      
    <div class="row">
      <div class="col-md-6">    
        <%= f.label :origin_id, "Origem"%>
        <%= f.collection_select(:origin_id, State.all, :symbol, :name, {:include_blank => true}, {:class=> "jstates form-control "}) %>
      </div>
      <div class="col-md-6">
        <%= f.label :origin_city_id, "Cidade"%>
        <%= f.grouped_collection_select :origin_city_id, State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {:class=> "jcities form-control "} %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">          
        <%= f.label :destination_id, "Destino" %>
        <%= f.collection_select(:destination_id, State.all, :symbol, :name, {:include_blank => true}, {:class=> "form-control jstates"}) %>
      </div>
      <div class="col-md-6">          
        <%= f.label :destination_city_id, "Cidade" %>
        <%= f.grouped_collection_select :destination_city_id, State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {:class=> "jcities form-control margin-bottom"} %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <%= f.label :start_date, "Saída" %>
        <%#= f.datetime_select :start_date, {:minute_step => 10}, {:id => 'datetimepicker'} %>
        <%#= f.text_field :start_date, { :class=> "form-control", :id=>"datetimepicker3"} %>
        <%= f.text_field :start_date, { :class=> "form-control datetimepicker4"} %>
      </div>
      <div class="col-md-6">
        <%= f.label :return_date, "Retorno" %>
        <%#= f.datetime_select :return_date, :minute_step => 10 %>
        <%= f.text_field :return_date, { :class=> "form-control datetimepicker4" } %>
      </div>
    </div>

    <%= f.label :Mensagem %>
    <%= f.text_area :annotation, class: "form-control", style: "height:300x" %>
    
    <div class="row">
      <div class="col-md-6">   
        <%= f.label :rate, "Qtd. Diárias"%>
        <%= f.text_field :rate, class: "form-control"%>
      </div>
      <div class="col-md-6">   
        <%= f.label :price, "Valor"%>
        <%= f.text_field :price, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">   
      <%= f.label :status %>
      <%= f.select :status, ['Aberto', 'Analisando',  'Pago'], {}, {:class=> "form-control margin-bottom"} %>
      </div>
    <div class="col-md-8">
      <%= f.submit "Criar Requisição", class: "btn btn-primary form-control margin-top" %>
    </div>
    <% end %>
  
</div>

app/views/tickets/show.html.erb
<% if @ticket.status == 'Pago' %>



<style type="text/css">
a { color: black;text-decoration: none; } 
a:hover { color: black;text-decoration: none; }
th a { display: block; }
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:2px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-yw4l{vertical-align:top}
</style>

  <div class="container margin-top">
    <% if @ticket.deleted_at? %>
    Requisição Apagada! 
    <li><%= link_to "VOLTAR <<", new_ticket_path %></li>
    <% else %>
  <table class="tg" width="700" border="2">
    
      <th class="tg-yw4l" colspan="2"><!--<a href="https://diarias-mohloko.c9users.io/">-->REQUISIÇÃO DE VIAGEM <!--</a>--><b>NO. <%= @ticket.id %></b></th>
      <th class="tg-yw4l" colspan="2">Data da Solicitação <%= @ticket.created_at.strftime("%d/%m/%Y") %></th>
    </tr>
    <tr>
      <td class="tg-yw4l" colspan="4"><b>Dados do Motorista</b></td>
    </tr>
    <tr>
      <td class="tg-yw4l" colspan="3"> Motorista: <%= @ticket.driver.name %></td>
      <td class="tg-yw4l">CPF: <%= @ticket.driver.cpf %></td>
    </tr>
    <tr>
      <% if @ticket.user.department.nil? %>
        <td class="tg-yw4l" colspan="4">Unidade Requisitante: --- </td>
        <% else %>
          <td class="tg-yw4l" colspan="4">Unidade Requisitante: <%= @ticket.user.department.name %></td>
        <% end %>
    </tr>
    <tr>
      <td class="tg-yw4l">Banco: <%= @ticket.driver.banco %></td>
      <td class="tg-yw4l">Agência: <%= @ticket.driver.agencia %></td>
      <td class="tg-yw4l">Conta: <%= @ticket.driver.conta %></td>
      <td class="tg-yw4l">Tipo Op: <%= @ticket.driver.operation %></td>
    </tr>
    <tr>
      <td class="tg-yw4l" colspan="4"><b>Dados da Viagem</b></td>
    </tr>
    <tr>
      <td class="tg-yw4l" colspan="2">Início da Viagem: <%= @ticket.start_date.strftime("%d/%m/%Y %H:%M") %></td>
      <td class="tg-yw4l" colspan="2">Origem: <%= @ticket.origin_city_id %> - <%= @ticket.origin_id %></td>
    </tr>
    <tr>
      <td class="tg-yw4l" colspan="2">Fim da Viagem: <%= @ticket.return_date.strftime("%d/%m/%Y %H:%M") %></td>
      <td class="tg-yw4l" colspan="2">Destino: <%= @ticket.destination_city_id %> - <%= @ticket.destination_id %></td>
    </tr>
    <tr>
      <td class="tg-yw4l" colspan="2">Qtd Diárias: <%= @ticket.rate %></td>
      <td class="tg-yw4l" colspan="2">Valor Total Diárias: <%= number_to_currency(@ticket.price, :unit => "R$ ", :separator => ",", :delimiter => ".")%></td>
    </tr>
  </table>
  <% end %>
</div>
<% else %>
  <%= render 'layouts/header' %>
<% end %>