config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users
  #match '/users',   to: 'users#index',   via: 'get'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  
  
 
  #resources :users, only: [:index, :show, :edit, :update, :destroy]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets
  
  resources :drivers
  
  resources :departments
  root to: "tickets#index"
end

app/models/driver.rb
# == Schema Information
#
# Table name: drivers
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  banco      :string
#  agencia    :string
#  conta      :string
#  operation  :string
#  cpf        :string
#

class Driver < ApplicationRecord
  require 'cpf_cnpj'
  validate :checkcpf

  private
  
  def checkcpf
    if !CPF.valid?(self.cpf)
      errors.add(:base, "CPF inválido")
    end
  end
  

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  
  def index
    @drivers = Driver.all
  end
  
  def show
    @driver = Driver.find(params[:id])
    
  end
  
  def new
    @driver = Driver.new
    
  end
  
  def create
    @driver = Driver.new(driver_params)
    if @driver.save
      flash[:success] = "Motorista cadastrado com sucesso!"
      redirect_to @driver
    else
      flash[:error] = @driver.errors.to_a
      render 'new'
    end
  end
  
  def edit 
    @driver = Driver.find(params[:id])
  end
  
  def update
    @driver = Driver.find(params[:id])
    if @driver.update_attributes(driver_params)
      flash[:success] = "Motorista atualizado!"
      redirect_to @driver
    else
      render 'edit'
    end
  end
  
  def destroy
    Driver.find(params[:id]).destroy
    flash[:success] = "Motorista excluído!"
    redirect_to users_url
  end
  
  private
  
  def driver_params
    params.require(:driver).permit(:name, :banco, :agencia, :conta, :operation, :cpf)
  end
  
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/edit.html.erb
<div class="container">
  <h1>Editar Motorista</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <%= form_for(@driver) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name,  { :class=> "form-control" } %>
           
      <%= f.label :cpf, "CPF" %>
      <%= f.text_field :cpf, { :class=> "form-control", :data => {:mask=> '999-999-9999'} }  %>
      
      <%= f.label :banco, "Banco" %>
      <%= f.text_field :banco, { :class=> "form-control" } %>
      
      <%= f.label :agencia, "Agência" %>
      <%= f.text_field :agencia, { :class=> "form-control" } %>
      
      <%= f.label :conta, "Conta" %>
      <%= f.text_field :conta, { :class=> "form-control" } %>
      
      <%= f.label :operation, "Tipo de Operação" %>
      <%= f.text_field :operation, { :class=> "form-control" } %>
      
      <%#= f.select :groups, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>

      <%#= f.select :group_ids, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
          
      <%= f.submit  "Cadastrar Motorista",        class:  "margin-top btn-primary form-control" %>
    <% end %>
  </div>
</div>
</div>

app/views/drivers/index.html.erb
<div class="container">
  <h1>Motoristas</h1>
  <ul class="drivers">
    <% @drivers.each do |driver| %>
      <li>
        <%= link_to driver.name, driver %>
        <% if current_user.role_id == 4 %>
           | <%= link_to "Editar", edit_driver_path(driver) %> | 
          <%= link_to "Excluir", driver, method: :delete, data: { confirm: "Tem certeza?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
  
</div>

app/views/drivers/new.html.erb
<script type="text/javascript">
function(){	
  $("#driver_cpf").mask("999.999.999-99")
;});

</script>
<div class="container">
  <h1>Criar Motorista</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <%= form_for(@driver) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name,  { :class=> "form-control" } %>
           
      <%= f.label :cpf, "CPF" %>
      <%= f.text_field :cpf, { :class=> "form-control", :data => {:mask=> '999-999-9999'} }  %>
      
      <%= f.label :banco, "Banco" %>
      <%= f.text_field :banco, { :class=> "form-control" } %>
      
      <%= f.label :agencia, "Agência" %>
      <%= f.text_field :agencia, { :class=> "form-control" } %>
      
      <%= f.label :conta, "Conta" %>
      <%= f.text_field :conta, { :class=> "form-control" } %>
      
      <%= f.label :operation, "Tipo de Operação" %>
      <%= f.text_field :operation, { :class=> "form-control" } %>
      
      <%#= f.select :groups, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>

      <%#= f.select :group_ids, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
          
      <%= f.submit  "Cadastrar Motorista",        class:  "margin-top btn-primary form-control" %>
    <% end %>
  </div>
</div>
</div>

app/views/drivers/show.html.erb
<div class="container">
<h1>Motorista</h1>

<div class="row">
  Nome: <%= @driver.name %> CPF: <%= @driver.cpf %>
</div>

<div class="row">
  Banco: <%= @driver.banco %>
</div>
<div class="row">
  Agência: <%= @driver.agencia %> Conta: <%= @driver.conta %>
</div>
<div class="row">
  Tipo de operação: <%= @driver.operation %>