config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users
  #match '/users',   to: 'users#index',   via: 'get'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  
  
 
  #resources :users, only: [:index, :show, :edit, :update, :destroy]

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets
  
  resources :drivers
  
  resources :departments
  root to: "tickets#index"
end

app/views/layouts/_header.html.erb
  <div class="container header">
    <% if logged_in? %>
      Bem vindo, <%= current_user.name %>!
    <% else %>
      
    <% end %>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", tickets_path %></li>
        
         <% if logged_in? %>
         <li class="dropdown">
           <a href="#"	class="dropdown-toggle"	data-toggle="dropdown">
             Requisições<b class="caret"></b>
             </a>
              <ul	class="dropdown-menu">
               <li><%= link_to "Listar", tickets_path %></li>
               <li><%= link_to "Cadastrar", new_ticket_path %></li>
              </ul>
          
          <% if current_user.role_id == 4 %>
            <li class="dropdown">
              <a href="#"	class="dropdown-toggle"	data-toggle="dropdown">
                Cadastros<b class="caret"></b>
              </a>
              <ul	class="dropdown-menu">
                <li><%= link_to "Listar Usuários", users_path %></li>
                <li><%= link_to "Cadastrar Usuário", new_user_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Listar Unidades", departments_path %></li>
                <li><%= link_to "Cadastrar Unidade", new_department_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Listar Motoristas", drivers_path %></li>
                <li><%= link_to "Cadastrar Motorista", new_driver_path %></li>
              </ul>
               
            <% end %>
          
			    <li><%#= link_to "show_index_of_users", users_path %></li>
				  <li	class="dropdown">
				    <a href="#"	class="dropdown-toggle"	data-toggle="dropdown">
				      Minha Conta<b class="caret"></b>
					  </a>
				    <ul	class="dropdown-menu">
					    <li><%#=	link_to	"Perfil",	current_user	%></li>
						  
						  <li><%#= link_to('Edit registration', edit_user_registration_path) %></li>
						  <li><%= link_to "Editar Conta", edit_user_path(current_user) %></li>


						  <li	class="divider"></li>
						  <li>
                <%= link_to "Sair", logout_path, method: "delete" %>
						    <%#= link_to('Logout', destroy_user_session_path, method: :delete) %>
						  </li>
            </ul>
          </li>
        <% else	%>
        		  <%#= link_to('Login', new_user_session_path)  %>
        		  
              <li><%= link_to "Log in", login_path %></li>
			  <% end	%>
      </ul>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controle de Requisição</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag 'application', media: 'screen', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    'print', media: 'print', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'print', :media => 'print' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%#= render 'layouts/messages' %>
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
	        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'alert') %>
	     	  toastr['<%= type %>']('<%= f[1] %>');
	      <% end %>
      </script>
    <% end %>
    
    <%= yield %>
    
    

  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'screen', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    'print', media: 'print', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'print', :media => 'print' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    
  </head>

  <body>
    
    <%#= render 'layouts/messages' %>
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
	        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'alert') %>
	     	  toastr['<%= type %>']('<%= f[1] %>');
	      <% end %>
      </script>
    <% end %>
    
    <%= yield %>
    
    

  </body>
</html>